### ISSUE TITLE
解除禁言时发生 IllegalArgumentException: durationSeconds must greater than zero

### ISSUE THREAD

**Issue by ForteScarlet** [simple-robot/simbot-component-mirai#58]
See https://github.com/ForteScarlet/simpler-robot/issues/411 by @Chenyuxin221

**Comment by ForteScarlet** [comment]
已在 https://github.com/simple-robot/simbot-component-mirai/commit/35c8951ea49bd4d868dcfa05e59e24bc8d53148d 中修复，可通过快照版本 `v3.0.0.0-beta-M2-SNAPSHOT` 提前验证并在仍有问题时继续反馈。@Chenyuxin221

**Comment by Chenyuxin221** [comment]
如何获取快照版本

**Comment by ForteScarlet** [comment]
> 如何获取快照版本

配置快照仓库，然后使用快照版本。

在 `pom.xml` 中：

```xml
<repositories>
    <repository>
        <id>sonatype-snapshot</id>
        <name>Sonatype Snapshots Repository</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

在 `build.gradle.kts` 中：

```kotlin
repositories {
    // ...
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
        mavenContent {
            snapshotsOnly()
        }
    }
}
```

**Comment by Chenyuxin221** [comment]
`Could not find artifact love.forte.simbot.component:simbot-component-mirai-boot:pom:v3.0.0.0-beta-M2-SNAPSHOT in sonatype-snapshot (https://oss.sonatype.org/content/repositories/snapshots/)`
URL使用浏览器打开提示**Directory listing forbidden**

**Comment by ForteScarlet** [comment]
> Could not find artifact love.forte.simbot.component:simbot-component-mirai-boot:pom:v3.0.0.0-beta-M2-SNAPSHOT in sonatype-snapshot

不要带着那个 `v`

**Comment by Chenyuxin221** [comment]
更新后问题以解决
