### ISSUE TITLE
为图片资源提供上传API

### ISSUE THREAD

**Issue by 954L** [simple-robot/simbot-component-mirai#95]
### 版本号

v3.0.0-M2

### 疑问描述

看到`bot.uploadImageBlocking()`已过时，替代的为`Image.of(Resource)`
想知道在后续版本中是否会删除uploadImageBlocking接口？如果删除是否有其他upload替代接口？
因为我主要是先upload拿到id后，下次发相同的图片就不需要再upload了，直接用`bot.resolveImageBlocking()`就能得到图片，且速度也很快。
但是如果每次都是用`Image.of(Resource)`的话，好像是每次都会upload

**Comment by ForteScarlet** [comment]
这个问题之前考虑过，不过我好像给忘了。后续会考虑为 `MiraiSendOnlyImage` 这个对象类型添加上传相关api，也会考虑提供一些对应对象上传图片的api（例如 MiraiGroup.uploadImage）

**Comment by 954L** [comment]
> 这个问题之前考虑过，不过我好像给忘了。后续会考虑为 `MiraiSendOnlyImage` 这个对象类型添加上传相关api，也会考虑提供一些对应对象上传图片的api（例如 MiraiGroup.uploadImage）

谢谢

**Comment by ForteScarlet** [comment]
功能完成后由我们来关闭此议题
